### ISSUE TITLE
how to *actually* use?

### ISSUE THREAD

**Issue by nonchip** [little-bear-labs/js-libp2p-webrtc#58]
since the `@libp2p/webrtc` package your readme claims this is, **does not actually exist**, i tried `little-bear-labs/js-libp2p-webrtc`, which gives me the sources without a `dist`, soooooooo, how is this supposed to work then?

**Comment by ckousik** [comment]
Sorry, `@libp2p/webrtc` does not exist yet. We are in the process of moving this library to the libp2p org. We'll fix the README. As for the build issue, we are looking into it.

**Comment by ckousik** [comment]
@nonchip We have added a prepare script which should build the packages when you run npm install. This will be removed once we can create an official release. Sorry for the inconvenience.
